export const CUSTOMERS_UPDATE = 'CUSTOMERS_UPDATE';
export const CUSTOMER_UPDATE = 'CUSTOMER_UPDATE';
export const CUSTOMER_DETAIL_UPDATE = 'CUSTOMER_DETAIL_UPDATE';
export const TRANSFER_EXECUTED = 'TRANSFER_EXECUTED';
export const TRANSFER_ERROR = 'TRANSFER_ERROR';
export const RESET_ERROR = 'RESET_ERROR';